### ISSUE TITLE
kdy bude tri.txt?

### ISSUE THREAD

**Issue by Wunson** [MarrekNozka/hracka#1]
dychtivě čekáme

**Comment by romansvozil** [comment]
👍

**Comment by thejoeejoee** [comment]
já taky čekám

**Comment by romansvozil** [comment]
@MarrekNozka Could you merge the branche into master please? We're still waiting 😿

**Comment by MarrekNozka** [comment]
Tři bude dnes. Ani nevíte jak jsem rád, že mi tak hezky pomáháte s názornou výukou. Doufám, že vás těší, že se stanete slavní! :sunglasses:

**Comment by MarrekNozka** [comment]
Hotovo
